### ISSUE TITLE
LNbank no lightning balance with v1.7.0

### ISSUE THREAD

**Issue by setavenger** [dennisreimann/btcpayserver-plugin-lnbank#13]
**Plugin**
Name and version of the plugin. 
LNbank v1.3.4.0

**Describe the bug**
Can't create lightning invoices and there is no balance shown 

**To Reproduce the bug**
Steps to reproduce the reported bug:
have BTCPay v1.7.x and LNbank v1.3.4.0

**Expected behavior**
should be able to create a lightning invoice and see the balance

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:    v1.7.0.0 and v1.7.1.0
- Lightning implementation  LND
- Deployment Method:        Docker
- Browser:                  Brave

**Logs (if applicable)**
12/03/2022 13:47:13:Error NodeInfo failed to be fetched: Error while connecting to the API: Connection refused (btcpay.21btcpay.com:443) (Connection refused)

**Comment by dennisreimann** [comment]
Can you upgrade LNbank to v1.3.7 (via "Manage Plugins") and see if it fixes this issue?

**Comment by setavenger** [comment]
Unfortunately still not seeing my balance or able to create an invoice

**Comment by dennisreimann** [comment]
Ok, can you redo the connection on the Lightning node settings page?

If it still doesn't work afterwards, what does the connection string look like? You can find it on the Lightning node settings page when you switch to the "Custom Node".

**Comment by setavenger** [comment]
Yeah did that a couple of times. The connection string looks like this:
"type=lnbank;server=https://{example.com}/;api-token=e490deab7b91863d4ad0b8e8e652d89b95a3a7ed"

**Comment by dennisreimann** [comment]
Turns out this is a DNS problem, wherein the `/etc/hosts` file had an entry that resolved the domain to `localhost`.

Once that was removed, it worked again.

Use `ping` to debug: `ping domain-from-server-string.com` should point to the correct IP. It it resolves to some local IP, find out where that is defined (most likely `/etc/hosts`) and remove that mapping.
