### ISSUE TITLE
Invoices are not settled

### ISSUE THREAD

**Issue by downet** [dennisreimann/btcpayserver-plugin-lnbank#15]
**Plugin**
LNbank 1.2.3.0

**Describe the bug**
Payment is payed (I can see it in ThunderHub), but it's not settled in BTCPayServer

**To Reproduce the bug**
To be honest, I have no idea how to correctly reproduce the error.

**Expected behavior**
Payment to be settled

**Screenshots**

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version:     v1.6.3.0
- Plugin Name and Version   LNbank  1.2.3.0
- Deployment Method:        Umbrel
- Browser:                  Brave
- LN implementation: LND 

**Logs (if applicable)**
I will deliver logs later.

**Comment by jaonoctus** [comment]
![image](https://user-images.githubusercontent.com/7918067/210114313-135520b1-eb5b-4ddf-864a-72b8e3f0c0a1.png)

![image](https://user-images.githubusercontent.com/7918067/210114327-2f202524-fc34-4bd2-8c8b-d9e493750ba1.png)

- BTCPayServer: `v1.7.3.0+09d5f5a08`
- LNbank: `v1.3.8.0`
- LND: `v0.15.4-beta commit=basedon-v0.15.4-beta-1-fresh-btcpay`

**Comment by dennisreimann** [comment]
@jaonoctus can you also post the log from the BTCPay container?

**Comment by jaonoctus** [comment]
@dennisreimann 
Sorry, I just updated to the last version and seems to be working now. 🙏🏻
