### ISSUE TITLE
[Bug]: Invoice is not marked as settled with the new checkout page when LN payment is made to LNBank

### ISSUE THREAD

**Issue by pavlenex** [dennisreimann/btcpayserver-plugin-lnbank#22]
https://github.com/btcpayserver/btcpayserver/issues/4408

**Comment by ishristov** [comment]
@dennisreimann, ca you take a look? I'm adding my description from the original issue:

>I made a LN payment with the new checkout UI and the store is configured to receive the payment to a LNBank wallet.
When I made the payment, the sats were received to the LNBank, but the invoice is still shown as "new" and the checkout page stays on the QR code as if nothing happened.

>I've seen this behaviour (payments to LNBank) very often and have reported bugs in the past. It gets resolved with the next update but then at some point it stops working again. Since the idea is to move to ln payments, is there something that can be done so that this lnbank regression doesn't happen that often? :)
