### ISSUE TITLE
LNUrl View could need a Close (X) or "back" button

### ISSUE THREAD

**Issue by petzsch** [dennisreimann/btcpayserver-plugin-lnbank#27]
I know browsers have a back button, but on other places we also incoperate a close/back button in these screens that don't show the navigation shown. So maybe just a minor nit pick to consider:

![grafik](https://user-images.githubusercontent.com/1374810/223456908-02479f69-867c-4710-84cf-41af0cf9f6af.png)

**Comment by dennisreimann** [comment]
This page is meant to be shared with people who want to pay you. In that case there would be no page to go back to. Imho the fix is to open this page in a separate window/tab and not have a close or back button.
