### ISSUE TITLE
Redundant config option for routing hints to private channels

### ISSUE THREAD

**Issue by petzsch** [dennisreimann/btcpayserver-plugin-lnbank#28]
These two settings should be doing the same thing?

![grafik](https://user-images.githubusercontent.com/1374810/223458045-dc0407f3-3ec0-4ef9-a1be-c3c770943afe.png)

and here:

![grafik](https://user-images.githubusercontent.com/1374810/223458149-9307b102-a543-41ae-a0a8-8064c9717538.png)

Perhaps the later one can go then?

**Comment by dennisreimann** [comment]
Nope, one is for the BTCPay store Lightning invoices and the other one is for a LNbank wallet. That wallet can be used independent of a store and settings for those transactions might differ.

**Comment by petzsch** [comment]
OK, that aspect I didn't see. But what about seemingly conflicting configurations? will BTCPay be able to show routing hints on it's invoices if (option 1 is on and option 2 is off) for example.

**Comment by dennisreimann** [comment]
Yes, but that's intended as those are two different contexts: 1 is for the Lightning invoices created via the store, 2 for manual transactions done within the LNbank wallet.
