### ISSUE TITLE
Plugin have to add "Access-Control-Allow-Origin: *" to well-known's lnurlp response

### ISSUE THREAD

**Issue by Perlover** [dennisreimann/btcpayserver-plugin-lnbank#31]
I don't know, your plugin is responsible for the Lightning Address inside BTCPay. But it seems to me that yours is.

It is highly desirable for other applications that your plugin adds an HTTP header "Access-Control-Allow-Origin: *" to the response when generating a response to the URL /.well-known/lnurlp/user. This is not the case now.

This header is very necessary, for example, for cases when payment to Lightning Address comes from web applications. Without this header, the browser policy will not allow third-party JavaScript code from other origins to receive an lnurlp's response . For example, it can be Nostr web applications for sending ZAPs. Or other cases

**Comment by dennisreimann** [comment]
LNbank doesn't have Lightning Addresses, yet. The Lightning Addresses inside BTCPay Server are managed [here](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UILNURLController.cs#L368) — that endpoint has CORS enabled.

As you mentioned it, the [Nostr plugin](https://github.com/Kukks/BTCPayServerPlugins/blob/master/Plugins/BTCPayServer.Plugins.NIP05/Nip5Controller.cs#L184) has CORS enabled for the zaps endpoint as well.

Can you elaborate a bit on which versions you are using and in which scenario it doesn't work for you?

**Comment by dennisreimann** [comment]
I just saw that you alreay opened issues on the Nostr plugin, so I'm going to close this as LNbank most likely isn't involved here.

**Comment by Perlover** [comment]
> that endpoint has CORS enabled.

I don't quite understand that code, but in fact it doesn't work. Here is the BTCPay instance on my server:

https://pay.fuckedbitcoin.com/.well-known/lnurlp/perlover

Response with headers is:

```
HTTP/2 200 OK
server: nginx
date: Wed, 26 Apr 2023 12:24:12 GMT
content-type: application/json; charset=utf-8
content-length: 417
onion-location: http://td6kgwiqljmjz3afikzv3a5e4iuw6a4y2g6akmrb7zezvifnlmpmbwad.onion/.well-known/lnurlp/perlover
content-security-policy: script-src 'self'
referrer-policy: same-origin
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: DENY
strict-transport-security: max-age=31536000
X-Firefox-Spdy: h2
```

CORS enabled is (example for nginx): https://www.w3.org/wiki/CORS_Enabled#For_nginx

But in response no `Access-Control-Allow-Origin:` * header

**Comment by dennisreimann** [comment]
I need to dig deeper why the header isn't present, but when running this in the web console it works:

![grafik](https://user-images.githubusercontent.com/886/234578390-23ff5591-9b70-480e-af1d-e6f5312f45fc.png)

What kind of code isn't working for you?

**Comment by Perlover** [comment]
I'm sorry! That's right and CARS is working! I checked without specifying the Origin header in the request. As soon as I specify it, the server exposes the header. Thanks for the clarification! :)

**Comment by dennisreimann** [comment]
No problem, glad you were able to resolve it!
