### ISSUE TITLE
Unable to close out LNbank wallet due to fee reserve

### ISSUE THREAD

**Issue by ryenski** [dennisreimann/btcpayserver-plugin-lnbank#32]
The [documentation states](https://docs.btcpayserver.org/LNbank/): 

> To remove a LNbank wallet, it must be emptied out first and have no balance left.

When trying to send the balance of funds from an LNbank wallet, I get an error like the following: 

```
Payment failed: Insufficient balance: 7107 sats - tried to send 7107 sats and need to keep a fee reserve of 213210 millisats.
```

![Xnapper-2023-05-17-14 41 39](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/234/39dfb871-9296-4538-86da-8912be472b16)

I subtracted 214 sats (213210 milisats) from the transaction, and it went through. However, now there is a stuck balance of 214 sats in the wallet. 

My goal is to remove this wallet; how can I sweep the balance in spite of the fee reserve?

**Comment by dennisreimann** [comment]
Yeah, I agree, that's annoying. I think I'll introduce a threshold (e.g. `10.000 sats`) below which the fee reserve won't be required when emptying out the wallet.

**Comment by ryenski** [comment]
What about a "sweep" function that moves the balance into another wallet on or into the main lightning balance, and then also deletes the wallet?

**Comment by dennisreimann** [comment]
Internally you can already transfer the funds without a fee reserve. Afterwards the wallet can be deleted. 

I will soon publish v1.5.1 that allows it in the way I described above.

**Comment by dennisreimann** [comment]
Check out [v1.5.1](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/releases/tag/v1.5.1) :)
