### ISSUE TITLE
Payment received by LNBANK, associated invoice was not marked settled.

### ISSUE THREAD

**Issue by damanic** [dennisreimann/btcpayserver-plugin-lnbank#34]
**VERSIONS**
- BTCPay Server v1.9.3+781190a65 
- LNBANK v1.5.1 

**BTCPAYSERVER (BTCPS) INVOICE**
- Created: 27/05/2023, 01:24
- Expired: 27/05/2023, 01:39
- Lightning payment request ID: lnbc4580650….
  
![image](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/5227303/d4cc8ccc-9ac5-410e-8d26-fe77ce638ff9)

**CUSTOMER PAYMENT**
- Received: 27/05/2023, 01:25
- For Lightning payment request ID: lnbc4580650….

![image](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/5227303/eb1d2175-e6c0-4b75-ae0a-f2e51ebfdfb8)

----

**Expected behaviour:** 
BTCPS invoice should have been marked as settled.

**Actual behaviour:** 
BTCPS invoice expired

@dennisreimann 
Can you confirm the issue here, and any guidance on how to fix the link between payment and invoice would be greatly appreciated. 

We are accounting based on BTCPS invoice reports, and tracking payments in ecommerce application based on BTCPS invoice status,  so we are keen to figure out how to prevent this issue from occurring again, and a way to correct the 'broken' invoice.

**Comment by dennisreimann** [comment]
We fixed it just this week (#33) and will release the fixed version with BTCPay Server v1.10 next week. 

You can manually mark the invoice as settled in BTCPay Server. Sorry for the inconvenience!

**Comment by damanic** [comment]
Good to hear, thanks.

Will the update repair affected invoice(s), by linking the payment and marking as settled?

**Comment by dennisreimann** [comment]
A server restart might help as well with that. It depends on wether or not the invoice watching expired.

**Comment by iBobik** [comment]
Just tried restart, not marked.

**Comment by dennisreimann** [comment]
Sorry, then you have to mark it manually from the invoice details or invoices list. We'll ship the fox with v1.10 next week — closing this, sorry once more for the inconveniences.

**Comment by damanic** [comment]
@dennisreimann 

There is no option to `mark it manually` on the list view or on the detail view:
![image](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/5227303/20d0c47d-4d61-4358-8250-5e0f7430c602)

We may have to open an issue related to this bug if there is no way to mend the broken transaction/invoice history.   Do you know of any other way to force the invoice to correct?

If a payment has been received by LNBANK but the associated invoice has not been updated  ( because of a bug, server downtime, whatever reason), there needs to be way to repair.  Otherwise the records in database are in an unexpected state which has potential to cause other issues. Certainly causing us issues in accounts report, and ecommerce integration.

Perhaps LNBANK needs to implement a sync/fix action that can repair any broken links between lnbank payments and btcinvoices?

**Comment by dennisreimann** [comment]
@damanic @iBobik We are addressing this in btcpayserver/btcpayserver#5006
