### ISSUE TITLE
Withdraw send wrong balance

### ISSUE THREAD

**Issue by iBobik** [dennisreimann/btcpayserver-plugin-lnbank#35]
Hi,
great work about new Withdraw feature! I just was not successful on a first try:

I currently have 896132 sats on the LNbank account.

Created unlimited withdraw code, opened it in Breez and tried to pull all 896000 sats which was less than was visible in Breez as available to pull.

Error Insufficient balance and need to keep a fee reserve:
![breez error](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/614232/a41f6137-189b-4c32-9d66-78b83132cfcd)

**Comment by dennisreimann** [comment]
As the error states, there needs to be a fee reserve which is higher in this case. Try withdrawing 893000 sats, that should work.

**Comment by iBobik** [comment]
I was successful finally, but it should not send amount it cannot process in the first lnurl call.Honza Pobořil💬Signal14. 7. 2023 v 8:11, d11n ***@***.***>:﻿
As the error states, there needs to be a fee reserve which is higher in this case. Try withdrawing 893000 sats, that should work.

**Comment by dennisreimann** [comment]
Agreed, will fix this :)
