### ISSUE TITLE
Allowing sending/reorganizing between LN Banks 

### ISSUE THREAD

**Issue by jacobburrell** [dennisreimann/btcpayserver-plugin-lnbank#37]
[Inherent current limitation of LND](https://github.com/lightningnetwork/lnd/issues/7419)

> the LND Accounts feature (https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/accounts). Currently, invoices are not able to be paid between two accounts using the same LND node.

Trying to do so currently returns an error message: 
`Self-payments Not Allowed`

Meaning users with different Ln Banks cannot send to another user with another Ln Bank on the same server.

Eliminating the possibility of a circular economy on a single node, which while requires trust, is highly effective for bootstrapping lots of users with very small amounts.

**Comment by dennisreimann** [comment]
Hey, see [this comment](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/issues/14#issuecomment-1357460816) — does that work for you?
