### ISSUE TITLE
It's possible to create a lightning address to lnbank wallet?

### ISSUE THREAD

**Issue by ncornejod** [dennisreimann/btcpayserver-plugin-lnbank#38]
I am developing a wallet app , and I found the the lnbank plugin in btcpay, but could be great if to every wallet I can create the lighning address (user@mydomain.com) 

I saw BTCPAY has the Lightning address option , but is for stores. 

Do you have guys some Idea how can I do it with lnbank?

**Comment by dennisreimann** [comment]
This is not possible right now, but I want to add it in the future. Meanwhile you can use the individual LNURL pay code that each wallet has and which you can find in the wallet's settings.
