### ISSUE TITLE
Show balance of lnbank liabilities to admins

### ISSUE THREAD

**Issue by nerdyrugbyguy** [dennisreimann/btcpayserver-plugin-lnbank#40]
The warning when lnbank liabilities exceed lightning funds is a great feature.  I had the warning come up, but I don't know how much I need to deposit to fix it.  Can the total of liabilities be displayed to admins?  This would also allow me to maintain off-chain funds that other admins could audit.  Would also help to see lnbank balances of individual users in case I needed to freeze or close their account.

**Comment by dennisreimann** [comment]
The admin overview has all of that data and also access to the individual wallets. You can get to it by following the settings link in the top right corner omce you are at your own wallets overview page.

**Comment by nerdyrugbyguy** [comment]
I see that admin gets total access to edit user account history and spend user funds.
