### ISSUE TITLE
The real withdraw "Spendable amount per use" doubles with each request

### ISSUE THREAD

**Issue by Perlover** [dennisreimann/btcpayserver-plugin-lnbank#43]
Hi,

BTCPay v1.11.6+44a7e9387 + LNBank v1.7.3

I am creating a withdrawal request with a limit, for example, 100 sats at a time ("Spendable amount per use" field under "Withdraw Configurations" section in Settings). But with each scan and  withdraw, the "maximum amount" limit actually doubles for each next withdraw request (I used Blixt wallet). Thus, if I scan 5 times, the withdrawal limit will not be 100 sats, but about 32 times more - about 3200 (minus 3%, which are deducted by the BTCPay server as a reservation for lightning fees). This works in all types of output frequency of withdraw

**Comment by dennisreimann** [comment]
Thanks for reporting, fixed in LNbank v1.8.0
