### ISSUE TITLE
Autofill "Description" with "Comment" if Description is empty

### ISSUE THREAD

**Issue by foghardrolls** [dennisreimann/btcpayserver-plugin-lnbank#44]
Hello and thank you very much for this great software!

I have a small suggestion if I may. When I send funds from one account to the LNURL of another account via the webGUI, I can enter text in the "Description" and "Comment" fields. But when I use BlueWallet to do the same, I can only enter text in "Comment". So the text only appears on the recipient account but not on the sender account.

Would it be possible to fill "Description" with the value of "Comment" if "Description" is empty? This way both accounts would see the text in their transactions list

**Comment by dennisreimann** [comment]
Hey, just so that I get it right: You are using the BlueWallet app as a frontend for a LNbank wallet and are sending to someone's LNURL. For that transaction you specify a LNURL comment and want that to also be attached to your transaction as a description on the LNbank side, right?

**Comment by foghardrolls** [comment]
Hello Dennis and thanks for your help. Here are my answers:

> You are using the BlueWallet app as a frontend for a LNbank wallet
Correct

> and are sending to someone's LNURL
Correct. To be precise, I am sending to the LNURL of another LNbank account (in the same LNbank)

> For that transaction you specify a LNURL comment
Correct. I would also specify a "description" if I could, but it's not possible via BlueWallet

> and want that to also be attached to your transaction as a description on the LNbank side, right?
Correct. When I look at the LNbank sender and recipient accounts for such a transaction, the comment appears on the recipient account but not on the sender account

**Comment by dennisreimann** [comment]
Unfortunately that's not possible, as the comment (LNURL) isn't part of the Lightning payment flow and LNbank does not know about it, because BlueWallet is handling that on the client-side. LNbank only gets to see the memo/description attached to the BOLT11 payment request — that's also why the UI in LNbank when paying to a LNURL offers to specify both, the comment and description.
