### ISSUE TITLE
Add CORS to API Endpoint

### ISSUE THREAD

**Issue by zoop-btc** [dennisreimann/btcpayserver-plugin-lnbank#47]
Hi Dennis,

Since this plugin exposes some endpoints for easy config it would make sense to add CORS so them much like it is for the rest of BTCPayServer. Otherwise browser applications cannot access it.

Thank you and best regards,
Zoop

**Comment by zoop-btc** [comment]
I'd like to have CORS available on all endpoints on `api/v1/lnbank/wallets` which is basically all of them as far as I can tell.

**Comment by dennisreimann** [comment]
Released with LNbank v1.8.5.
