### ISSUE TITLE
Receiving via LN address doesn't show in corresponding LN Bank wallet

### ISSUE THREAD

**Issue by jacobburrell** [dennisreimann/btcpayserver-plugin-lnbank#55]
I set an LN address `jacob@pay.revoluciones.mx` with an LN wallet and sent sats from [Strike](https://strike.me/) to that address successfully, but the funds never showed in the tx list and also seems to not reflect in the balance.

However, the funds did arrive and show up when looking at the node directly in e.g. RTL

**Comment by dennisreimann** [comment]
Is this Lightning Address maybe already taken by a store in BTCPay? The [response here](https://pay.revoluciones.mx/.well-known/lnurlp/jacob) doesn't look like it is served by LNbank, so I assume that's the case. 

BTCPay first checks core for Lightning Addresses (associated with stores) and if not found it falls back to lookup the Lightning Address via plugins.

**Comment by jacobburrell** [comment]
Where in BTCPayServer is LN address per store defined? I don't see it in Store settings.

If so, then LN bank should check during LN address assignment of both LN bank and BTCPay LN address to ensure no duplicates exist.

Setting the same address to different wallets is a confusing UX, no?

**Comment by jacobburrell** [comment]
plugins/lightning-address 

Yes there is a conflict with the above plugin assigning the same address.

As they are both plugins this conflict makes sense.

Would be great if there was some central server wide place to keep track of and thus allow us to prevent this.

Ideas for fix @dennisreimann ?

**Comment by dennisreimann** [comment]
Yes, I'll add a check for that in one of the upcoming versions. Thanks for bringing this up!

**Comment by satscoffee** [comment]
I may have a similar issue...I have the LNbank plugin, which works well overall! Thank you. However I was getting errors when trying to pay via the lightning address generated from my LNbank (hey@btcpay.sats.coffee). The errors included "Failed to call on the given LNURL" in mutiny and "invoice dexcription_hash doesn't match metadata" in bluewallet and zeus.

However if I create the same exact lightning address using the lightning address for the general btcpayserver module, it works well, but only arrives in my btcpay general wallet, not the LNbank, which makes sense. If I delete the general btcpay lightning address and keep the LNbank lightning address, it fails again. It is currently enabled only in the LNbank plugin address as of now.

Happy to help troubleshoot to get this working. Thank you!

**Comment by dennisreimann** [comment]
@satscoffee The [Lightning Address response](https://btcpay.sats.coffee/.well-known/lnurlp/hey) looks good to me and I was able to pay to that address just fine with Zeus and Alby, so I assume it might maybe be related to outdated Zeus and BlueWallet versions?

**Comment by dennisreimann** [comment]
Do the store Lightning Addresses in BTCPay work for you? Even the [callback response](https://btcpay.sats.coffee/plugins/lnbank/api/lnurl/49e11587-39c2-45a8-b412-82d3173a6ff0/pay-callback?amount=1000) seems to be just fine and return an invoice, so I'm not sure why the wallets you mentioned complain.

> Is there any guidance you can provide in how I should "address" with the wallet devs?

I think you can post issues mentioning those two response URLs and their JSON, so that they can debug it.

**Comment by satscoffee** [comment]
Just tried using the store's Lightning Address (tips@btcpay.sats.coffee), and it worked fine in Strike and Phoenix, payment was accepted but is pending in Mutiny, and BlueWallet accepted the address but got error "No_Route"...

Seems like the issue occurs when using the lightning address created from the LNbank account for some wallets. I'll post to those wallets, but is there anything different on the callback response or address response etc. from the store vs. the LNbank?

**Comment by dennisreimann** [comment]
The only difference I can see is an additional empty `["text/plain",""]` in the metadata for the store response. Reading [the spec](https://github.com/lnurl/luds/blob/luds/06.md) this shouldn't make a difference — or does it, @kukks?
