### ISSUE TITLE
Negative Balance

### ISSUE THREAD

**Issue by jacobburrell** [dennisreimann/btcpayserver-plugin-lnbank#56]
Steps taken:

1. Make a LN Bank Wallet
2. Receive 100 sats
3. Send 100 sats
4. See error message regarding object

![image](https://github.com/dennisreimann/btcpayserver-plugin-lnbank/assets/61520543/6182c445-2a75-4d96-89a8-0b7efb4d8781)

**Comment by dennisreimann** [comment]
Yup, will fix this. The -200 sats is incorrect, as these are actually millisats and the balance being negative is due to the fact that below a certain threshold the fees don't get deducted, so that people can sweep the wallet. Will adjust the display for that.
