### ISSUE TITLE
If lnbank is used as source for the store, the POS never feels the payment

### ISSUE THREAD

**Issue by massmux** [dennisreimann/btcpayserver-plugin-lnbank#61]
btcpay 1.12
lnbank updated latest today

If lnbank is used as source for the store, the POS never feels the payment. If i change lightning to a different source (for example an external lndhub) pos works normally

**Comment by massmux** [comment]
Just seen another bug

if i am on "internal node" and then choose lnbank, i can specify the dropdown with the wallet name. When i choose it and click save a white page is displayed and the setting is not configured

**Comment by dennisreimann** [comment]
Can you check if this is still the case with BTCPay v1.12.1 and LNbank v1.9.0? You might have to reconnect the wallet to the store with the error you described here: 

> When i choose it and click save a white page is displayed and the setting is not configured

**Comment by massmux** [comment]
yes the bug of the change of source is resolved in the new version. also the problem of lnbank seems resolved. unfortunately prism is no more working. pity i used it a lot

**Comment by dennisreimann** [comment]
Ok, thanks for getting back on this. I see the prism issue is already tracked in Kukks/BTCPayServerPlugins#28, hopefully this gets resolved soon too.
